export interface CountryCode {
    code: string;
    dial: string;
    name: string;
    flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
    { code: 'US', dial: '+1',   name: 'United States',  flag: '🇺🇸' },
    { code: 'BR', dial: '+55',  name: 'Brazil',          flag: '🇧🇷' },
    { code: 'GB', dial: '+44',  name: 'United Kingdom',  flag: '🇬🇧' },
    { code: 'CA', dial: '+1',   name: 'Canada',          flag: '🇨🇦' },
    { code: 'AU', dial: '+61',  name: 'Australia',       flag: '🇦🇺' },
    { code: 'DE', dial: '+49',  name: 'Germany',         flag: '🇩🇪' },
    { code: 'FR', dial: '+33',  name: 'France',          flag: '🇫🇷' },
    { code: 'ES', dial: '+34',  name: 'Spain',           flag: '🇪🇸' },
    { code: 'IT', dial: '+39',  name: 'Italy',           flag: '🇮🇹' },
    { code: 'PT', dial: '+351', name: 'Portugal',        flag: '🇵🇹' },
    { code: 'MX', dial: '+52',  name: 'Mexico',          flag: '🇲🇽' },
    { code: 'AR', dial: '+54',  name: 'Argentina',       flag: '🇦🇷' },
    { code: 'CO', dial: '+57',  name: 'Colombia',        flag: '🇨🇴' },
    { code: 'CL', dial: '+56',  name: 'Chile',           flag: '🇨🇱' },
    { code: 'PE', dial: '+51',  name: 'Peru',            flag: '🇵🇪' },
    { code: 'IN', dial: '+91',  name: 'India',           flag: '🇮🇳' },
    { code: 'CN', dial: '+86',  name: 'China',           flag: '🇨🇳' },
    { code: 'JP', dial: '+81',  name: 'Japan',           flag: '🇯🇵' },
    { code: 'KR', dial: '+82',  name: 'South Korea',     flag: '🇰🇷' },
    { code: 'RU', dial: '+7',   name: 'Russia',          flag: '🇷🇺' },
    { code: 'NG', dial: '+234', name: 'Nigeria',         flag: '🇳🇬' },
    { code: 'ZA', dial: '+27',  name: 'South Africa',    flag: '🇿🇦' },
    { code: 'EG', dial: '+20',  name: 'Egypt',           flag: '🇪🇬' },
    { code: 'AE', dial: '+971', name: 'UAE',             flag: '🇦🇪' },
    { code: 'SA', dial: '+966', name: 'Saudi Arabia',    flag: '🇸🇦' },
    { code: 'IL', dial: '+972', name: 'Israel',          flag: '🇮🇱' },
    { code: 'NL', dial: '+31',  name: 'Netherlands',     flag: '🇳🇱' },
    { code: 'SE', dial: '+46',  name: 'Sweden',          flag: '🇸🇪' },
    { code: 'NO', dial: '+47',  name: 'Norway',          flag: '🇳🇴' },
    { code: 'DK', dial: '+45',  name: 'Denmark',         flag: '🇩🇰' },
    { code: 'FI', dial: '+358', name: 'Finland',         flag: '🇫🇮' },
    { code: 'PL', dial: '+48',  name: 'Poland',          flag: '🇵🇱' },
    { code: 'CH', dial: '+41',  name: 'Switzerland',     flag: '🇨🇭' },
    { code: 'AT', dial: '+43',  name: 'Austria',         flag: '🇦🇹' },
    { code: 'BE', dial: '+32',  name: 'Belgium',         flag: '🇧🇪' },
    { code: 'SG', dial: '+65',  name: 'Singapore',        flag: '🇸🇬' },
    { code: 'NZ', dial: '+64',  name: 'New Zealand',      flag: '🇳🇿' },
    { code: 'TH', dial: '+66',  name: 'Thailand',          flag: '🇹🇭' },
    { code: 'VN', dial: '+84',  name: 'Vietnam',           flag: '🇻🇳' },
    { code: 'ID', dial: '+62',  name: 'Indonesia',         flag: '🇮🇩' },
    { code: 'MY', dial: '+60',  name: 'Malaysia',          flag: '🇲🇾' },
    { code: 'PH', dial: '+63',  name: 'Philippines',       flag: '🇵🇭' },
    { code: 'PK', dial: '+92',  name: 'Pakistan',          flag: '🇵🇰' },
    { code: 'BD', dial: '+880', name: 'Bangladesh',        flag: '🇧🇩' },
    { code: 'TW', dial: '+886', name: 'Taiwan',            flag: '🇹🇼' },
    { code: 'HK', dial: '+852', name: 'Hong Kong',         flag: '🇭🇰' },
    { code: 'CZ', dial: '+420', name: 'Czech Republic',    flag: '🇨🇿' },
    { code: 'HU', dial: '+36',  name: 'Hungary',           flag: '🇭🇺' },
    { code: 'RO', dial: '+40',  name: 'Romania',           flag: '🇷🇴' },
    { code: 'GR', dial: '+30',  name: 'Greece',            flag: '🇬🇷' },
    { code: 'IE', dial: '+353', name: 'Ireland',           flag: '🇮🇪' },
    { code: 'UA', dial: '+380', name: 'Ukraine',           flag: '🇺🇦' },
    { code: 'TR', dial: '+90',  name: 'Turkey',            flag: '🇹🇷' },
    { code: 'HR', dial: '+385', name: 'Croatia',           flag: '🇭🇷' },
    { code: 'SK', dial: '+421', name: 'Slovakia',          flag: '🇸🇰' },
    { code: 'BG', dial: '+359', name: 'Bulgaria',          flag: '🇧🇬' },
    { code: 'KE', dial: '+254', name: 'Kenya',             flag: '🇰🇪' },
    { code: 'ET', dial: '+251', name: 'Ethiopia',          flag: '🇪🇹' },
    { code: 'GH', dial: '+233', name: 'Ghana',             flag: '🇬🇭' },
    { code: 'TZ', dial: '+255', name: 'Tanzania',          flag: '🇹🇿' },
    { code: 'MA', dial: '+212', name: 'Morocco',           flag: '🇲🇦' },
    { code: 'VE', dial: '+58',  name: 'Venezuela',                       flag: '🇻🇪' },
    { code: 'EC', dial: '+593', name: 'Ecuador',                         flag: '🇪🇨' },
    { code: 'UY', dial: '+598', name: 'Uruguay',                         flag: '🇺🇾' },
    { code: 'BO', dial: '+591', name: 'Bolivia',                         flag: '🇧🇴' },
    { code: 'PY', dial: '+595', name: 'Paraguay',                        flag: '🇵🇾' },
    { code: 'GY', dial: '+592', name: 'Guyana',                          flag: '🇬🇾' },
    { code: 'SR', dial: '+597', name: 'Suriname',                        flag: '🇸🇷' },
    { code: 'CR', dial: '+506', name: 'Costa Rica',                      flag: '🇨🇷' },
    { code: 'PA', dial: '+507', name: 'Panama',                          flag: '🇵🇦' },
    { code: 'GT', dial: '+502', name: 'Guatemala',                       flag: '🇬🇹' },
    { code: 'HN', dial: '+504', name: 'Honduras',                        flag: '🇭🇳' },
    { code: 'NI', dial: '+505', name: 'Nicaragua',                       flag: '🇳🇮' },
    { code: 'SV', dial: '+503', name: 'El Salvador',                     flag: '🇸🇻' },
    { code: 'BZ', dial: '+501', name: 'Belize',                          flag: '🇧🇿' },
    { code: 'CU', dial: '+53',  name: 'Cuba',                            flag: '🇨🇺' },
    { code: 'DO', dial: '+1',   name: 'Dominican Republic',              flag: '🇩🇴' },
    { code: 'HT', dial: '+509', name: 'Haiti',                           flag: '🇭🇹' },
    { code: 'JM', dial: '+1',   name: 'Jamaica',                         flag: '🇯🇲' },
    { code: 'TT', dial: '+1',   name: 'Trinidad and Tobago',             flag: '🇹🇹' },
    { code: 'BB', dial: '+1',   name: 'Barbados',                        flag: '🇧🇧' },
    { code: 'BS', dial: '+1',   name: 'Bahamas',                         flag: '🇧🇸' },
    { code: 'LC', dial: '+1',   name: 'Saint Lucia',                     flag: '🇱🇨' },
    { code: 'VC', dial: '+1',   name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
    { code: 'GD', dial: '+1',   name: 'Grenada',                         flag: '🇬🇩' },
    { code: 'AG', dial: '+1',   name: 'Antigua and Barbuda',             flag: '🇦🇬' },
    { code: 'KN', dial: '+1',   name: 'Saint Kitts and Nevis',           flag: '🇰🇳' },
    { code: 'DM', dial: '+1',   name: 'Dominica',                        flag: '🇩🇲' },
    { code: 'QA', dial: '+974', name: 'Qatar',                           flag: '🇶🇦' },
    { code: 'KW', dial: '+965', name: 'Kuwait',            flag: '🇰🇼' },
    { code: 'JO', dial: '+962', name: 'Jordan',            flag: '🇯🇴' },
];
